development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:25746e4fe925847be9a2cb0e98c45973@soapfish.redistogo.com:11747/
  channel_prefix: math_kata_production
